//! `Task` — the on-disk record for a single async-spawned worker.
//!
//! One task → one directory under `<cache>/jarvis/tasks/<id>/`:
//!
//! ```text
//! tasks/
//!   t-1715701234-a3f7c1/
//!     record.json    — this struct, serialised
//!     stdout.txt     — captured stdout (written by E1-3's watcher)
//!     stderr.txt     — captured stderr
//! ```
//!
//! Spec 0011's E1-1 lands the schema and the save/load round-trip;
//! the spawn / watcher / notification mechanics arrive in E1-3.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Lifecycle of a task. `Running` is the only non-terminal state;
/// the others can transition to nothing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskStatus {
    /// Spawned, child PID is alive (or believed alive — the
    /// startup orphan check in E1-2 may flip this to `Orphaned`).
    Running,
    /// Child exited 0.
    Completed,
    /// Child exited non-zero (signal kill, normal failure, etc.).
    Failed,
    /// `jarvis task cancel <id>` sent SIGTERM and the child
    /// exited as a result.
    Cancelled,
    /// Daemon found the record with status=Running on startup but
    /// the PID is gone (daemon crashed mid-task) or the spawn
    /// machinery lost track of it. No completion-time guarantee.
    Orphaned,
}

impl TaskStatus {
    pub fn is_terminal(self) -> bool {
        !matches!(self, TaskStatus::Running)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Task {
    /// Generated by [`task_id`]; sortable by spawn time.
    pub id: String,
    /// The conversational thread that spawned this task. Lets
    /// `jarvis task list` default to the current thread when
    /// multi-thread arrives (out of scope here).
    pub thread_id: String,
    /// Which worker handled the task — manifest id or built-in
    /// handler id.
    pub worker_id: String,
    /// Unix seconds when the task was spawned.
    pub spawn_time: u64,
    /// Unix seconds when the child exited. `None` while running.
    pub completion_time: Option<u64>,
    pub status: TaskStatus,
    /// What the user originally asked for, in their own words.
    /// Surfaces verbatim in `jarvis task list` so the user can
    /// recognise the task.
    pub user_intent: String,
    /// The argv used to spawn the child. Kept for debugging and
    /// for future "rerun this task" UX.
    pub command: Vec<String>,
    /// Child PID while `Running`; cleared on terminal states so
    /// nothing tries to signal a dead process.
    pub pid: Option<u32>,
    /// Exit code of the child once it terminates. `None` for
    /// `Orphaned` tasks where the daemon never observed the exit.
    pub exit_code: Option<i32>,
    /// Short human-readable summary of the task's output. Today
    /// it's the first ~500 chars of stdout (filled by the watcher
    /// in E1-3); auto-summarisation via an LLM is deferred to v2.
    pub summary: Option<String>,
}

impl Task {
    /// Build a fresh task record in `Running` state. The caller
    /// (E1-3's spawn machinery) sets `pid` after the spawn
    /// succeeds and then [`save`](Self::save)s.
    pub fn new(
        worker_id: impl Into<String>,
        command: Vec<String>,
        user_intent: impl Into<String>,
        thread_id: impl Into<String>,
    ) -> Self {
        let spawn_time = unix_now();
        Self {
            id: task_id(spawn_time),
            thread_id: thread_id.into(),
            worker_id: worker_id.into(),
            spawn_time,
            completion_time: None,
            status: TaskStatus::Running,
            user_intent: user_intent.into(),
            command,
            pid: None,
            exit_code: None,
            summary: None,
        }
    }

    /// Directory for this task under the given `base` cache root.
    pub fn dir(&self, base: &Path) -> PathBuf {
        base.join(&self.id)
    }

    pub fn record_path(&self, base: &Path) -> PathBuf {
        self.dir(base).join("record.json")
    }

    pub fn stdout_path(&self, base: &Path) -> PathBuf {
        self.dir(base).join("stdout.txt")
    }

    pub fn stderr_path(&self, base: &Path) -> PathBuf {
        self.dir(base).join("stderr.txt")
    }

    /// Atomic write: serialise to `<dir>/record.json.tmp`, then
    /// rename. Crashes mid-write can't leave a truncated record.
    /// Creates the task directory if needed.
    pub fn save(&self, base: &Path) -> Result<()> {
        let dir = self.dir(base);
        fs::create_dir_all(&dir)
            .with_context(|| format!("creating task dir: {}", dir.display()))?;
        let path = self.record_path(base);
        let tmp = path.with_extension("json.tmp");
        let json = serde_json::to_string_pretty(self).context("serialising task record")?;
        fs::write(&tmp, json).with_context(|| format!("writing {}", tmp.display()))?;
        fs::rename(&tmp, &path)
            .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
        Ok(())
    }

    /// Load a record from `<base>/<id>/record.json`. Returns `Err`
    /// for IO / parse failure; callers (registry load) treat a
    /// failed load as "skip this directory and warn".
    pub fn load(base: &Path, id: &str) -> Result<Task> {
        let path = base.join(id).join("record.json");
        let raw =
            fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
        let task: Task =
            serde_json::from_str(&raw).with_context(|| format!("parsing {}", path.display()))?;
        Ok(task)
    }
}

/// Generate a task id of the form `t-<unix>-<6-hex-tail>` where the
/// 6-hex tail is derived from the nanosecond clock so two tasks
/// spawned in the same second still get distinct ids. Sorts
/// lexicographically by spawn time, which `jarvis task list` relies
/// on for stable newest-first ordering.
pub fn task_id(spawn_time_secs: u64) -> String {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    format!("t-{:010}-{:06x}", spawn_time_secs, nanos & 0xFF_FFFF)
}

fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn fixture_task() -> Task {
        Task::new(
            "gemini",
            vec![
                "gemini-cli".to_string(),
                "--prompt".to_string(),
                "analyze syslog".to_string(),
            ],
            "analyze the system log and summarise errors",
            "s-test-thread",
        )
    }

    /// A fresh `Task::new` is in `Running` state with no
    /// completion time, exit code, or pid yet — those land in
    /// E1-3 when the spawn machinery wires up.
    #[test]
    fn task_new_starts_running() {
        let t = fixture_task();
        assert_eq!(t.status, TaskStatus::Running);
        assert!(t.completion_time.is_none());
        assert!(t.exit_code.is_none());
        assert!(t.pid.is_none());
        assert_eq!(t.worker_id, "gemini");
        assert!(t.id.starts_with("t-"));
    }

    /// Save + load round-trips every field through JSON. Catches
    /// any serde shape changes (renames, type-mismatch) before
    /// they reach disk.
    #[test]
    fn task_save_and_load_roundtrip() {
        let tmp = TempDir::new().unwrap();
        let mut t = fixture_task();
        // Populate the "later-lifecycle" fields so the roundtrip
        // exercises Some(...) for completion_time / exit_code etc.
        t.pid = Some(12345);
        t.completion_time = Some(unix_now() + 30);
        t.status = TaskStatus::Completed;
        t.exit_code = Some(0);
        t.summary = Some("found 3 errors".to_string());

        t.save(tmp.path()).expect("save succeeds");

        // The record landed at the expected nested path.
        let expected = tmp.path().join(&t.id).join("record.json");
        assert!(expected.exists(), "record.json at {}", expected.display());

        let loaded = Task::load(tmp.path(), &t.id).expect("load succeeds");
        assert_eq!(loaded.id, t.id);
        assert_eq!(loaded.worker_id, "gemini");
        assert_eq!(loaded.command, t.command);
        assert_eq!(loaded.status, TaskStatus::Completed);
        assert_eq!(loaded.exit_code, Some(0));
        assert_eq!(loaded.summary.as_deref(), Some("found 3 errors"));
        assert_eq!(loaded.pid, Some(12345));
    }

    /// Path helpers derive consistent sibling paths under the
    /// task's directory. Used by the watcher (E1-3) to write
    /// stdout/stderr alongside the record.
    #[test]
    fn path_helpers_share_task_dir() {
        let tmp = TempDir::new().unwrap();
        let t = fixture_task();
        let dir = t.dir(tmp.path());
        assert!(t.record_path(tmp.path()).starts_with(&dir));
        assert!(t.stdout_path(tmp.path()).starts_with(&dir));
        assert!(t.stderr_path(tmp.path()).starts_with(&dir));
        assert!(t.stdout_path(tmp.path()).ends_with("stdout.txt"));
        assert!(t.stderr_path(tmp.path()).ends_with("stderr.txt"));
    }

    /// `is_terminal` distinguishes `Running` from the four
    /// completed-form states. The watcher uses this to decide
    /// whether to keep polling.
    #[test]
    fn status_is_terminal_partitions_states() {
        assert!(!TaskStatus::Running.is_terminal());
        for s in [
            TaskStatus::Completed,
            TaskStatus::Failed,
            TaskStatus::Cancelled,
            TaskStatus::Orphaned,
        ] {
            assert!(s.is_terminal(), "{s:?} should be terminal");
        }
    }

    /// Atomic-write contract: a save into a non-existent dir
    /// creates the dir, drops no `.tmp` file behind, and lands a
    /// well-formed `record.json`.
    #[test]
    fn save_is_atomic_and_creates_dir() {
        let tmp = TempDir::new().unwrap();
        let t = fixture_task();
        t.save(tmp.path()).expect("save succeeds");
        let entries: Vec<_> = fs::read_dir(t.dir(tmp.path()))
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name())
            .collect();
        // Only the final record file, no leftover .tmp.
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0], "record.json");
    }

    /// `task_id` is `t-<10-digit-unix>-<6-hex>`. Same-second
    /// spawns get distinct ids because the hex tail comes from
    /// the nanosecond clock.
    #[test]
    fn task_id_format_is_sortable_and_unique() {
        let same_sec = 1_715_700_000_u64;
        let id_a = task_id(same_sec);
        // Tiny sleep so the nanosecond tail differs.
        std::thread::sleep(std::time::Duration::from_nanos(1000));
        let id_b = task_id(same_sec);
        assert!(
            id_a.starts_with("t-1715700000-"),
            "got: {id_a}"
        );
        assert!(
            id_b.starts_with("t-1715700000-"),
            "got: {id_b}"
        );
        assert_ne!(id_a, id_b, "same-second ids must differ in the hex tail");
    }
}
